In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
# now lets add 1 to it 
a+1 # doen't modify the original array

array([2, 3, 4, 5])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
a**2

array([ 1,  4,  9, 16])

In [8]:
# All arithmetic operates elementwise
b=np.ones(4)
b

array([1., 1., 1., 1.])

In [10]:
b=b+1
b


array([2., 2., 2., 2.])

In [11]:
a-b

array([-1.,  0.,  1.,  2.])

In [12]:
a*b

array([2., 4., 6., 8.])

## Matrix multipicatio

In [13]:
c=np.diag([1,2,3,4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
c*c

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [15]:
c.dot(c)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])